// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbRuqUYcR5CLEc7FltGY-T1ixdFkkXhZs',
    appId: '1:193297063920:web:b4902b59833bc107994735',
    messagingSenderId: '193297063920',
    projectId: 'cuentas10b',
    authDomain: 'cuentas10b.firebaseapp.com',
    storageBucket: 'cuentas10b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gyjKzgZCgmciRPitQdAS5SRRCI0VEuI',
    appId: '1:193297063920:android:331219895de7aae5994735',
    messagingSenderId: '193297063920',
    projectId: 'cuentas10b',
    storageBucket: 'cuentas10b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtArD2vF8BMjdXoxwQqqzzsnAHvhZxB20',
    appId: '1:193297063920:ios:1c58c027be51686d994735',
    messagingSenderId: '193297063920',
    projectId: 'cuentas10b',
    storageBucket: 'cuentas10b.appspot.com',
    iosBundleId: 'com.example.tareacuentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtArD2vF8BMjdXoxwQqqzzsnAHvhZxB20',
    appId: '1:193297063920:ios:1c58c027be51686d994735',
    messagingSenderId: '193297063920',
    projectId: 'cuentas10b',
    storageBucket: 'cuentas10b.appspot.com',
    iosBundleId: 'com.example.tareacuentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbRuqUYcR5CLEc7FltGY-T1ixdFkkXhZs',
    appId: '1:193297063920:web:db7a957b7a892d79994735',
    messagingSenderId: '193297063920',
    projectId: 'cuentas10b',
    authDomain: 'cuentas10b.firebaseapp.com',
    storageBucket: 'cuentas10b.appspot.com',
  );
}
